### ISSUE TITLE
Improve API reference documentation

### ISSUE THREAD

**Issue by jgarzik** [jgarzik/kvdbd#11]
The [current API reference](https://github.com/jgarzik/kvdbd/blob/master/doc/api.md) leaves a lot to be desired.  Use modern tools to create something better.

**Comment by RLSDev** [comment]
Do you have a preferred tool?

**Comment by jgarzik** [comment]
> Do you have a preferred tool?

No preferred tool, only preferred parameters:   Reproducible without cost by all developers - which typically implies open source tools.

**Comment by Quadrisheriff** [comment]
Hi I am a newbie technical writer, can I take on your project?

**Comment by jgarzik** [comment]
> Hi I am a newbie technical writer, can I take on your project?

Of course!   The normal process is simply creating Pull Requests with the necessary changes, and they will be reviewed and merged (if approved, or revisions will be requested)

**Comment by Sukkoto** [comment]
@jgarzik I'd like to contribute. I'm completely new to Git and RESTful API docs. Has any progress been made since you opened this issue?

I'm learning as I go, so I will be working very slowly, but I'll do my best. Will you let me help?
